development:
  adapter: postgresql
  encoding: unicode
  database: buildtree_development
  pool: 5
  username: buildtree
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: buildtree_test
  pool: 5
  username: buildtree
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRES_DATABASE"] || 'buildtree_production' %>
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || 'buildtree' %>
  password: <%= ENV["POSTGRES_PASS"] %>
  host: <%= ENV["POSTGRES_HOST"] || 'localhost' %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>
